# Generated by Django 4.2.6 on 2023-10-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.TextField()),
                ('description', models.TextField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
